name: Hot Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        バグレポートにご協力いただきありがとうございます！
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: もっと情報が必要な場合、どのように連絡すればよいですか？
      placeholder: ex. email@example.com or Discord User Name
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きましたか？
      description: また、どのようなことが起こると予想しましたか？
      placeholder: Tell us what you see!
      value: "バグの詳細"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: どのOSで問題が発生していますか？
      multiple: true
      options:
        - macOS Monterey
        - macOS Ventura
        - macOS Sonoma
        - Windows
  - type: textarea
    id: logs
    attributes:
      label: 発生したエラーや警告、このバグレポートに関係するログ
      description: 関連するログ出力をコピー＆ペーストしてください。これは自動的にコードにフォーマットされますので、バックティックは必要ありません。
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: この問題を提出することにより、あなたは私たちの[行動規範](https://example.com)に従うことに同意します。
      options:
        - label: 私はこのプロジェクトの行動規範に従うことに同意します。
          required: true